# Checklist.yaml
#Basic Configurations
provider: aws
accounts:
  # Account : name of account alias
  # Role Arn : Assume role that is used for original account to assume to access the cross account
  - name: prerpod
    role_arn: arn:client:iam::11111...

# Regions to scan
regions:
  - ap-northeast-2
#  - us-east-1
#  - us-east-2
#  - us-west-1
#  - us-west-2

resources:
#  - name: ec2
#  - name: security_group
#  - name: route53
#  - name: rds
#  - name: s3
  - name: iam
