[en]
  title = "ZDoc"
  languageName = "English"
  weight = 1
  contentdir = "content/en"

#[ko_not_used]
#  title = "ZDoc"
#  languageName = "한국어"
#  weight = 2
#  contentdir = "content/ko_not_used"
